---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'config/**'
      - 'debian/**'
      - 'doc/**'
      - 'subprojects/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'config/**'
      - 'debian/**'
      - 'doc/**'
      - 'subprojects/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcap-dev \
            libfmt-dev \
            libseccomp-dev \
            libsystemd-dev \
            libdbus-1-dev \
            libpq-dev \
            libluajit-5.1-dev

      - name: Configure
        run: |
          meson setup \
            -Ddocumentation=disabled \
            -Dwrap_mode=nofallback \
            output

      - name: Build
        run: ninja -C output -v
